# Generated by Django 4.2.3 on 2023-07-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contacts_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='subject',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
