# Generated by Django 4.2.3 on 2023-07-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelTable(
            name='cars',
            table='Cars',
        ),
    ]
