# Generated by Django 4.2.3 on 2023-07-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_cars_doors_alter_cars_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
            ],
            options={
                'verbose_name_plural': 'Car_images',
                'db_table': 'CarImages',
            },
        ),
    ]
