# Generated by Django 4.2.3 on 2023-07-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
