# Generated by Django 4.2.3 on 2023-07-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_cars_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='slug',
        ),
    ]
