# Generated by Django 4.2.3 on 2023-07-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_remove_cars_milage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
    ]
