# Generated by Django 4.2.3 on 2023-07-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('banner', models.ImageField(upload_to='banner/')),
                ('address', models.TextField()),
                ('phone_number', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Setting',
                'db_table': 'Setting',
            },
        ),
    ]
