# Generated by Django 4.2.3 on 2023-07-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0003_remove_setting_address_remove_setting_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('google_plus_link', models.URLField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Contact',
                'db_table': 'Contact',
            },
        ),
    ]
